name: ZenGuides
author: Herring Cove
baseurl: /ZenGuides
description: theme for jekyll
github: http://www.github.com/hsavit1
twitter: http://www.twitter.com/FeelSomeFLow
 facebook: http://www.facebook.com
 linkedin: http://www.linkedin.com

email: henrysavit[at]me.com
location: 42°2'16"N   70°12'47"W
disqus: MathPhysicsFlow

##Make sure to edit the above fields, especially for disqus.


highlighter: pygments
markdown: redcarpet
redcarpet:
  extensions: ["tables"]

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
